SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i, ANIMAL_OUTS o
WHERE 1=1
    AND i.ANIMAL_ID = o.ANIMAL_ID
    AND i.SEX_UPON_INTAKE LIKE 'Intact%'
    AND ( o.SEX_UPON_OUTCOME LIKE 'Spayed%'
        OR o.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY i.ANIMAL_ID ASC;
